name: ASP
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - pytorch
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.8.3
  - libexpat=2.7.1
  - libffi=3.4.6
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libsqlite=3.50.4
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.5.3
  - pip=25.2
  - python=3.11.4
  - readline=8.2
  - setuptools=80.9.0
  - tk=8.6.13
  - tzdata=2025b
  - wheel=0.45.1
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - pip:
      - array-api-compat==1.12.0
      - audioread==3.0.1
      - certifi==2025.8.3
      - cffi==2.0.0
      - charset-normalizer==3.4.3
      - contourpy==1.3.3
      - cycler==0.12.1
      - decorator==5.2.1
      - fonttools==4.60.0
      - idna==3.10
      - joblib==1.5.2
      - kiwisolver==1.4.9
      - lazy-loader==0.4
      - librosa==0.11.0
      - llvmlite==0.45.1
      - matplotlib==3.10.6
      - msgpack==1.1.1
      - mtrf==2.1.2
      - numba==0.62.1
      - numpy==1.26.4
      - packaging==25.0
      - pandoc==2.4
      - pillow==11.3.0
      - platformdirs==4.4.0
      - plumbum==1.9.0
      - ply==3.11
      - pooch==1.8.2
      - pycparser==2.23
      - pyparsing==3.2.5
      - pypdf2==3.0.1
      - python-dateutil==2.9.0.post0
      - requests==2.32.5
      - scikit-learn==1.7.2
      - scipy==1.16.2
      - six==1.17.0
      - sounddevice==0.5.2
      - soundfile==0.13.1
      - soxr==1.0.0
      - threadpoolctl==3.6.0
      - typing-extensions==4.15.0
      - urllib3==2.5.0
prefix: /Users/logic/opt/anaconda3/envs/ASP
